quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRESQL_USER:parasol}
quarkus.datasource.password=${POSTGRESQL_PASSWORD:parasol}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRESQL_HOST:parasol-db}:5432/${POSTGRESQL_DATABASE:parasol}
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
%prod.kafka.bootstrap.servers=kafka-kafka-bootstrap.kafka.svc:9092
%prod.kafka.security.protocol=SASL_PLAINTEXT
%prod.kafka.sasl.mechanism=SCRAM-SHA-512
%prod.kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
    username="parasol" \
    password="${DEV_KAFKA_PASSWORD}";
mp.messaging.incoming.emails-in.connector=smallrye-kafka
mp.messaging.incoming.emails-in.topic=${KAFKA_TOPIC:intake}
mp.messaging.incoming.emails-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.emails-in.auto.offset.reset=latest
mp.messaging.incoming.emails-in.group.id=${HOSTNAME:parasol-email-router}

mp.messaging.outgoing.emails-out.connector=smallrye-kafka
mp.messaging.outgoing.emails-out.topic=${KAFKA_TOPIC:intake}
mp.messaging.outgoing.emails-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer
